apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pacman.fullname" . }}-mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $secretObj := lookup "v1" "Secret" .Release.Namespace (printf "%s-mongodb" (include "pacman.fullname" .)) }}
  {{- $secretData := ($secretObj).data | default dict }}
  {{- $existingPassword := index $secretData "mongodb-root-password" }}
  mongodb-root-password: {{ $existingPassword | default (randAlphaNum 32 | b64enc) | quote }}
